<?php
/**
 * Created by PhpStorm.
 * User: S.Karavaev
 * Date: 20.09.2018
 * Time: 22:54
 */

namespace Tests\Feature\Http\Contrllers\Api;

use App\Http\Requests\AbstractApiRequest;
use App\Domain\Entity\PbxScheme\NodeType;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class PbxSchemeControllerTest extends TestCase
{
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp();
    }

    public function testCreatePbxScheme()
    {
        $nodeType1 = new NodeType();
        $nodeType1->type = 'node';
        $nodeType1->name = 'announce';
        $nodeType1->deleted = false;
        $nodeType1->save();

        $nodeType2 = new NodeType();
        $nodeType2->type = 'condition';
        $nodeType2->name = 'ring_duration';
        $nodeType2->deleted = false;
        $nodeType2->save();

        $response = $this->json(
            'POST',
            '/api/1.0/pbx-scheme',
            [
                'nodes'     => [
                    [
                        'tmp_id'       => 'd87jdo90s',
                        'node_type_id' => $nodeType1->id,
                        'data'         => [
                            'testdata1' => 'value1',
                            'testdata2' => 'value2',
                        ],
                    ],
                    [
                        'tmp_id'       => 'd87j923hdk',
                        'node_type_id' => $nodeType2->id,
                        'data'         => [
                            'testdata3' => 'value3',
                            'testdata4' => 'value4',
                        ],
                    ],
                ],
                'relations' => [
                    [
                        'type'      => 'positive',
                        'from_node' => 'd87jdo90s',
                        'to_node'   => 'd87j923hdk',
                    ]
                ],
            ],
            [
                AbstractApiRequest::CUSTOM_HEADER_REQUEST_INITIATOR_USER_ID => 1,
            ]
        );

        dd($response);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
